[2019-04-23 09:54:36 -0400] [73777] [CRITICAL] WORKER TIMEOUT (pid:73781)
[2019-04-23 09:56:25 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73925)
[2019-04-23 09:56:25 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73919)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73920)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73921)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73922)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73923)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73924)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73990)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73926)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73927)
[2019-04-23 10:06:20 -0400] [73915] [CRITICAL] WORKER TIMEOUT (pid:73991)
[2019-04-23 10:08:54 -0400] [74159] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74160] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74161] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74162] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74163] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74164] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74166] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74165] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:08:54 -0400] [74167] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74200] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74201] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:14 -0400] [74202] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74203] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74204] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74205] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74206] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74207] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:15 -0400] [74208] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74264] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74265] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74266] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74267] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74268] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74270] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74269] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74271] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 10:09:59 -0400] [74272] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 48, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/abeukers/anaconda/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 77, in <module>
    from custom import custom_code
  File "/Users/abeukers/wd/csw/cswBehavioral/experiment_generation/csw_mturk_template/custom.py", line 65
    print subj_filler_score)
                           ^
SyntaxError: invalid syntax
[2019-04-23 16:04:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75845)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75846)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75851)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75853)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75855)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75858)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75859)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75860)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:75861)
[2019-04-23 17:11:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:77533)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78635)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78636)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78637)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78638)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78639)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78640)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78641)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78642)
[2019-04-23 18:05:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:78643)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80075)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80076)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80077)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80078)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80080)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80081)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80082)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80083)
[2019-04-23 18:56:56 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80084)
[2019-04-23 19:37:40 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80623)
[2019-04-23 19:37:40 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80632)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80910)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80911)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80624)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80626)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80627)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80628)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80629)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80630)
[2019-04-23 21:21:46 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:80631)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81615)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81616)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81618)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81619)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81620)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81621)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81622)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81623)
[2019-04-23 23:53:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:81624)
[2019-04-24 07:12:39 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82216)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82276)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82218)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82219)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82220)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82221)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82223)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82225)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82226)
[2019-04-24 08:33:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:82227)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83491)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83492)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83493)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83494)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83495)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83496)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83497)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83498)
[2019-04-24 08:40:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83499)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83584)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83585)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83586)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83587)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83588)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83589)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83590)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83591)
[2019-04-24 10:18:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:83592)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84343)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84344)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84345)
[2019-04-24 10:30:02 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84348)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84513)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84514)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84515)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84516)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84346)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84347)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84349)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84350)
[2019-04-24 12:01:38 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:84351)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86080)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86081)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86082)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86083)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86084)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86085)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86086)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86079)
[2019-04-24 13:16:08 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:86078)
[2019-04-24 14:44:36 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87239)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87240)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87241)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87242)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87243)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87244)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87245)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87237)
[2019-04-24 14:44:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:87238)
[2019-04-24 16:53:16 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88526)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88525)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88528)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88529)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88530)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88531)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88532)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88533)
[2019-04-24 16:53:17 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:88527)
[2019-04-24 19:22:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89090)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89091)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89092)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89094)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89083)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89084)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89086)
[2019-04-24 19:22:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89087)
[2019-04-24 19:41:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91904)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91905)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91906)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91907)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:89093)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91900)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91901)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91902)
[2019-04-24 19:41:55 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:91903)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92032)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92024)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92025)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92026)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92027)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92028)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92029)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92030)
[2019-04-24 20:03:24 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92031)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92288)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92290)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92291)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92292)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92293)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92294)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92289)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92297)
[2019-04-24 21:00:04 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92295)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92342)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92343)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92344)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92345)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92346)
[2019-04-24 21:56:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92347)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92389)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92390)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92391)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92392)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92394)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92348)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92349)
[2019-04-24 23:16:19 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92350)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92435)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92436)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92437)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92438)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92439)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92440)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92441)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92442)
[2019-04-24 23:22:42 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92393)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92490)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92491)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92492)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92493)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92494)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92495)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92496)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92497)
[2019-04-24 23:42:32 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92498)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92544)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92536)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92537)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92538)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92539)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92540)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92541)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92542)
[2019-04-25 00:19:51 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92543)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92580)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92581)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92582)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92583)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92585)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92586)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92587)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92588)
[2019-04-25 00:38:05 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92589)
[2019-04-25 00:52:14 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92633)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92686)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92634)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92635)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92636)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92637)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92638)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92639)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92640)
[2019-04-25 02:20:15 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92641)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92701)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92702)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92703)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92704)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92705)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92706)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92707)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92708)
[2019-04-25 03:22:10 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92700)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92754)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92755)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92756)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92757)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92758)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92759)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92760)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92761)
[2019-04-25 03:42:50 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92762)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92806)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92807)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92808)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92810)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92811)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92812)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92813)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92814)
[2019-04-25 04:17:37 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92815)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92876)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92877)
[2019-04-25 05:12:26 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92878)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92929)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92930)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92931)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92879)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92882)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92885)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92886)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92887)
[2019-04-25 06:12:41 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92888)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92953)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92954)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92955)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92956)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92957)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92958)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92959)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92960)
[2019-04-25 07:19:20 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92961)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:92999)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93000)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93001)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93002)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93003)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93004)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93005)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93006)
[2019-04-25 07:46:13 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93007)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93056)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93057)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93058)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93050)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93051)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93052)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93053)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93054)
[2019-04-25 07:49:29 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93055)
[2019-04-25 08:18:53 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93101)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93102)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93103)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93104)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93105)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93106)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93107)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93108)
[2019-04-25 08:18:54 -0400] [75771] [CRITICAL] WORKER TIMEOUT (pid:93109)
[2019-04-25 10:38:45 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:14484)
[2019-04-25 11:26:51 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:14488)
[2019-04-25 11:30:08 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:16319)
[2019-04-25 11:31:14,430] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3U5JL4WY5L5GS9ET68LEBQILL4OX4V'], 'workerId': [u'A191V7PT3DQKDP'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:31:21,322] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3U5JL4WY5L5GS9ET68LEBQILL4OX4V'], 'workerId': [u'A191V7PT3DQKDP'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:31:26,879] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3U5JL4WY5L5GS9ET68LEBQILL4OX4V'], 'workerId': [u'A191V7PT3DQKDP'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:31:34,577] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3U5JL4WY5L5GS9ET68LEBQILL4OX4V'], 'workerId': [u'A191V7PT3DQKDP'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:34:31,168] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'31Z0PCVWULB6UFNS3WIOPZHPZAS7T8'], 'workerId': [u'AG5HAUJJV4OCY'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:34:38 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:14486)
[2019-04-25 11:34:45,628] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3WJEQKOXA9YN4X9H8GAYTK0K8Z61AJ'], 'workerId': [u'A30UE6DWFNUCWX'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:38:56 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:14485)
[2019-04-25 11:38:56 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:14487)
[2019-04-25 11:42:29,723] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3S06PH7KSS0L24CTSQ10JL8QT231DL'], 'workerId': [u'A4T4577P6JL6R'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 11:46:29 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:15729)
[2019-04-25 11:52:03,049] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'37KGEN7NJ4MX8TYLI13LKB7DA1EPPT'], 'workerId': [u'AJW3PL5UDH4BP'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 12:30:29 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:16731)
[2019-04-25 12:43:00 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:16936)
[2019-04-25 12:57:56 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:17758)
[2019-04-25 13:26:16 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:17753)
[2019-04-25 13:30:18 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:16730)
[2019-04-25 13:30:29 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:17764)
[2019-04-25 14:36:58 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:19004)
[2019-04-25 14:43:12 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:16717)
[2019-04-25 14:43:12 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:18526)
[2019-04-25 14:43:19 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:19843)
[2019-04-25 15:58:20 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:19851)
[2019-04-25 16:34:32 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:19848)
[2019-04-25 16:34:44 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:20945)
[2019-04-25 17:35:43,804] ERROR in experiment: already_did_exp_hit (1010) {'assignmentId': [u'3WRFBPLXRBKQYJHL4OTM3JZH6RO3N5'], 'workerId': [u'AK4WZEW584BR9'], 'hitId': [u'30U1YOGZGASIA4EUF7BIR2ZDSYFSDK'], 'mode': [u'live']}
[2019-04-25 17:47:54 +0000] [14480] [CRITICAL] WORKER TIMEOUT (pid:19847)
